<!--
   Script.Script @ Male_Normal |  Initial_Values | Organ_Mass

   Created : 2012-03-04
   Revised : 2012-03-04
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<stats_local_reset/>

<accept>
  <var> Bone-Size.Mass </var>
  <min> 10000 </min>
  <max> 11000 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> Bone-Size.Mass </var>
  <datum> 10725 </datum>
  <tolerance> 400 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> Brain-Size.Mass </var>
  <min> 1450 </min>
  <max> 1550 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> Brain-Size.Mass </var>
  <datum> 1500 </datum>
  <tolerance> 50 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> Fat-Size.Mass </var>
  <min> 15500 </min>
  <max> 16500 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> Fat-Size.Mass </var>
  <datum> 16050 </datum>
  <tolerance> 500 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> GITract-Size.Mass </var>
  <min> 1250 </min>
  <max> 1300 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> GITract-Size.Mass </var>
  <datum> 1275 </datum>
  <tolerance> 60 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> Kidney-Size.Mass </var>
  <min> 320 </min>
  <max> 340 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> Kidney-Size.Mass </var>
  <datum> 330 </datum>
  <tolerance> 10 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> LeftHeart-Size.Mass </var>
  <min> 285 </min>
  <max> 300 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> LeftHeart-Size.Mass </var>
  <datum> 293 </datum>
  <tolerance> 10 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> Liver-Size.Mass </var>
  <min> 1900 </min>
  <max> 2000 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> Liver-Size.Mass </var>
  <datum> 1950 </datum>
  <tolerance> 80 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> OtherTissue-Size.Mass </var>
  <min> 3450 </min>
  <max> 3600 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> OtherTissue-Size.Mass </var>
  <datum> 3525 </datum>
  <tolerance> 100 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> RespiratoryMuscle-Size.Mass </var>
  <min> 3550 </min>
  <max> 3650 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> RespiratoryMuscle-Size.Mass </var>
  <datum> 3600 </datum>
  <tolerance> 100 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> RightHeart-Size.Mass </var>
  <min> 55 </min>
  <max> 65 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> RightHeart-Size.Mass </var>
  <datum> 60 </datum>
  <tolerance> 5 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> SkeletalMuscle-Size.Mass </var>
  <min> 26000 </min>
  <max> 27000 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> SkeletalMuscle-Size.Mass </var>
  <datum> 26400 </datum>
  <tolerance> 500 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> Skin-Size.Mass </var>
  <min> 2700 </min>
  <max> 2900 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> Skin-Size.Mass </var>
  <datum> 2775 </datum>
  <tolerance> 100 </tolerance>
  <format> 1 </format>
</quality>

<stats_local> Male Normal | Initial Values | Organ Mass </stats_local>

<comment> ==================================================== </comment>

<stats_local_details/>

<!-- End -->