<!--
   Script.Script @ Male_Normal |  Initial_Values | Organ_Mass

   Created : 2012-03-04
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> Bone-Size.Mass </var>
  <datum> 10725 </datum>
  <min> 10000 </min>
  <max> 11000 </max>
  <format> 1 </format>
</test>

<test>
  <var> Brain-Size.Mass </var>
  <datum> 1500 </datum>
  <min> 1450 </min>
  <max> 1550 </max>
  <format> 1 </format>
</test>

<test>
  <var> Fat-Size.Mass </var>
  <datum> 16050 </datum>
  <min> 15500 </min>
  <max> 16500 </max>
  <format> 1 </format>
</test>

<test>
  <var> GITract-Size.Mass </var>
  <datum> 1275 </datum>
  <min> 1250 </min>
  <max> 1300 </max>
  <format> 1 </format>
</test>

<test>
  <var> Kidney-Size.Mass </var>
  <datum> 330 </datum>
  <min> 320 </min>
  <max> 340 </max>
  <format> 1 </format>
</test>

<test>
  <var> LeftHeart-Size.Mass </var>
  <datum> 293 </datum>
  <min> 285 </min>
  <max> 300 </max>
  <format> 1 </format>
</test>

<test>
  <var> Liver-Size.Mass </var>
  <datum> 1950 </datum>
  <min> 1900 </min>
  <max> 2000 </max>
  <format> 1 </format>
</test>

<test>
  <var> OtherTissue-Size.Mass </var>
  <datum> 3525 </datum>
  <min> 3450 </min>
  <max> 3600 </max>
  <format> 1 </format>
</test>

<test>
  <var> RespiratoryMuscle-Size.Mass </var>
  <datum> 3600 </datum>
  <min> 3550 </min>
  <max> 3650 </max>
  <format> 1 </format>
</test>

<test>
  <var> RightHeart-Size.Mass </var>
  <datum> 60 </datum>
  <min> 55 </min>
  <max> 65 </max>
  <format> 1 </format>
</test>

<test>
  <var> SkeletalMuscle-Size.Mass </var>
  <datum> 26400 </datum>
  <min> 26000 </min>
  <max> 27000 </max>
  <format> 1 </format>
</test>

<test>
  <var> Skin-Size.Mass </var>
  <datum> 2775 </datum>
  <min> 2700 </min>
  <max> 2900 </max>
  <format> 1 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->