<!--
   Script.Script @ Male_Normal | Exercise_5_5_5_150W | 10_Minutes

   Created : 2012-03-05
   Revised : 2012-03-05
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center */
-->

<modeltitle/>
<timestamp/>

<stats_local_reset/>

<logpoint/>

<setvalue>
	<var> Exercise-Control.Request </var>
	<val> 1 </val>
</setvalue>

<setvalue>
	<var> Exercise-Bike.Power(W) </var>
	<val> 150 </val>
</setvalue>

<gofor>
  <solutionint> 5 </solutionint>
  <displayint> 0.5 </displayint>
</gofor>

<logpoint/>

<accept>
  <var> SystemicArtys.Pressure </var>
  <min> 95 </min>
  <max> 100 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> SystemicArtys.Pressure </var>
  <datum> 97 </datum>
  <tolerance> 3 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> SystemicArtys.SBP </var>
  <min> 118 </min>
  <max> 122 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> SystemicArtys.SBP </var>
  <datum> 120 </datum>
  <tolerance> 2 </tolerance>
  <format> 1 </format>
</quality>

<accept>
  <var> SystemicArtys.DBP </var>
  <min> 78 </min>
  <max> 82 </max>
  <format> 1 </format>
</accept>

<quality>
  <var> SystemicArtys.DBP </var>
  <datum> 80 </datum>
  <tolerance> 2 </tolerance>
  <format> 1 </format>
</quality>

<stats_local> Male Normal | Exercise 5-5-5 150W | 10 Minutes </stats_local>

<comment> ==================================================== </comment>

<stats_local_details/>

<!-- End -->