<!--
   Script.Script @ Female_Normal | Initial_Values | Body_Mass

   Created : 2012-03-04
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> Weight.Weight(kG) </var>
  <datum> 60.5 </datum>
  <min> 59 </min>
  <max> 62 </max>
  <format> 1 </format>
</test>

<test>
  <var> Weight.Weight(Lb) </var>
  <datum> 133 </datum>
  <min> 130.5 </min>
  <max> 135.5 </max>
  <format> 1 </format>
</test>

<test>
  <var> Adiposity.Mass </var>
  <datum> 19767 </datum>
  <min> 18500 </min>
  <max> 20500 </max>
  <format> 0 </format>
</test>

<test>
  <var> Muscularity.Mass </var>
  <datum> 14629 </datum>
  <min> 13500 </min>
  <max> 15500 </max>
  <format> 1 </format>
</test>

<test>
  <var> OtherMass.Mass </var>
  <datum> 20795 </datum>
  <min> 19700 </min>
  <max> 21700 </max>
  <format> 0 </format>
</test>

<test>
  <var> Weight-Fluids.Total </var>
  <datum> 5259 </datum>
  <min> 5150 </min>
  <max> 5350 </max>
  <format> 0 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->