<!--
   Script.Script @ HumMod(2_0)

   Created : 2012-03-03
   Revised : 2012-03-03
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<script>

<launch>
	<solver> J:\ModelSolver\Code\Model Solver.EXE </solver>
	<model> J:\HumModXML\HumMod.DES </model>
</launch>

<modeltitle/>
<timestamp/>

<reset/>
<restart/>

<?include Male_Normal/Script.Script ?>
<?include Female_Normal/Script.Script ?>

<stats_global> Total Stats </stats_global>

<newparagraph/>

<?include Environment/Script.Script ?>

</script>

<!-- End -->