<!--
   Script.Script @ Male_Normal | Exercise_5_5_5_150W | Starting

   Created : 2012-03-05
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center */
-->

<modeltitle/>
<timestamp/>

<logpoint/>

<test>
  <var> SystemicArtys.Pressure </var>
  <datum> 97 </datum>
  <min> 95 </min>
  <max> 100 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicArtys.SBP </var>
  <datum> 120 </datum>
  <min> 118 </min>
  <max> 122 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicArtys.DBP </var>
  <datum> 80 </datum>
  <min> 78 </min>
  <max> 82 </max>
  <format> 1 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->