<!--
   Script.Script @ Female_Normal | Initial_Values | Organ_Composition

   Created : 2012-03-04
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> Bone-Size.LiquidMass </var>
  <datum> 3432 </datum>
  <min> 3400 </min>
  <max> 3500 </max>
  <format> 0 </format>
</test>

<test>
  <var> Bone-Size.SolidMass </var>
  <datum> 7293 </datum>
  <min> 7200 </min>
  <max> 7300 </max>
  <format> 0 </format>
</test>

<test>
  <var> Bone-Size.MineralMass </var>
  <datum> 5543 </datum>
  <min> 5000 </min>
  <max> 6000 </max>
  <format> 0 </format>
</test>

<test>
  <var> Bone-Size.OtherMass </var>
  <datum> 1750 </datum>
  <min> 1700 </min>
  <max> 1800 </max>
  <format> 0 </format>
</test>

<test>
  <var> Brain-Size.LiquidMass </var>
  <datum> 1005 </datum>
  <min> 900 </min>
  <max> 1100 </max>
  <format> 0 </format>
</test>

<test>
  <var> Brain-Size.SolidMass </var>
  <datum> 495 </datum>
  <min> 480 </min>
  <max> 510 </max>
  <format> 0 </format>
</test>

<test>
  <var> Fat-Size.LiquidMass </var>
  <datum> 2408 </datum>
  <min> 2300 </min>
  <max> 2500 </max>
  <format> 0 </format>
</test>

<test>
  <var> Fat-Size.SolidMass </var>
  <datum> 13643 </datum>
  <min> 13000 </min>
  <max> 14000 </max>
  <format> 0 </format>
</test>

<test>
  <var> Fat-Size.LipidMass </var>
  <datum> 12142 </datum>
  <min> 12000 </min>
  <max> 13000 </max>
  <format> 0 </format>
</test>

<test>
  <var> Fat-Size.OtherMass </var>
  <datum> 1501 </datum>
  <min> 1490 </min>
  <max> 1510 </max>
  <format> 0 </format>
</test>

<test>
  <var> GITract-Size.LiquidMass </var>
  <datum> 854 </datum>
  <min> 800 </min>
  <max> 900 </max>
  <format> 0 </format>
</test>

<test>
  <var> GITract-Size.SolidMass </var>
  <datum> 421 </datum>
  <min> 410 </min>
  <max> 430 </max>
  <format> 0 </format>
</test>

<test>
  <var> Kidney-Size.LiquidMass </var>
  <datum> 221 </datum>
  <min> 210 </min>
  <max> 230 </max>
  <format> 0 </format>
</test>

<test>
  <var> Kidney-Size.SolidMass </var>
  <datum> 109 </datum>
  <min> 100 </min>
  <max> 120 </max>
  <format> 1 </format>
</test>

<test>
  <var> LeftHeart-Size.LiquidMass </var>
  <datum> 196 </datum>
  <min> 190 </min>
  <max> 210 </max>
  <format> 0 </format>
</test>

<test>
  <var> LeftHeart-Size.SolidMass </var>
  <datum> 97 </datum>
  <min> 90 </min>
  <max> 100 </max>
  <format> 1 </format>
</test>

<test>
  <var> LeftHeart-Size.ContractileProteinMass </var>
  <datum> 68 </datum>
  <min> 65 </min>
  <max> 75 </max>
  <format> 1 </format>
</test>

<test>
  <var> LeftHeart-Size.OtherMass </var>
  <datum> 29 </datum>
  <min> 27 </min>
  <max> 31 </max>
  <format> 1 </format>
</test>

<test>
  <var> Liver-Size.LiquidMass </var>
  <datum> 1307 </datum>
  <min> 1250 </min>
  <max> 1350 </max>
  <format> 0 </format>
</test>

<test>
  <var> Liver-Size.SolidMass </var>
  <datum> 644 </datum>
  <min> 635 </min>
  <max> 655 </max>
  <format> 0 </format>
</test>

<test>
  <var> OtherTissue-Size.LiquidMass </var>
  <datum> 2362 </datum>
  <min> 2300 </min>
  <max> 2400 </max>
  <format> 0 </format>
</test>

<test>
  <var> OtherTissue-Size.SolidMass </var>
  <datum> 1163 </datum>
  <min> 1100 </min>
  <max> 1200 </max>
  <format> 0 </format>
</test>

<test>
  <var> RespiratoryMuscle-Size.LiquidMass </var>
  <datum> 2844 </datum>
  <min> 2800 </min>
  <max> 2900 </max>
  <format> 0 </format>
</test>

<test>
  <var> RespiratoryMuscle-Size.SolidMass </var>
  <datum> 756 </datum>
  <min> 750 </min>
  <max> 765 </max>
  <format> 0 </format>
</test>

<test>
  <var> RespiratoryMuscle-Size.ContractileProteinMass </var>
  <datum> 378 </datum>
  <min> 370 </min>
  <max> 390 </max>
  <format> 0 </format>
</test>

<test>
  <var> RespiratoryMuscle-Size.OtherMass </var>
  <datum> 378 </datum>
  <min> 370 </min>
  <max> 385 </max>
  <format> 0 </format>
</test>

<test>
  <var> RightHeart-Size.LiquidMass </var>
  <datum> 40 </datum>
  <min> 38 </min>
  <max> 42 </max>
  <format> 1 </format>
</test>

<test>
  <var> RightHeart-Size.SolidMass </var>
  <datum> 20 </datum>
  <min> 19 </min>
  <max> 21 </max>
  <format> 1 </format>
</test>

<test>
  <var> RightHeart-Size.ContractileProteinMass </var>
  <datum> 14 </datum>
  <min> 13 </min>
  <max> 15 </max>
  <format> 1 </format>
</test>

<test>
  <var> RightHeart-Size.OtherMass </var>
  <datum> 6 </datum>
  <min> 5 </min>
  <max> 7 </max>
  <format> 1 </format>
</test>

<test>
  <var> SkeletalMuscle-Size.LiquidMass </var>
  <datum> 20856 </datum>
  <min> 20000 </min>
  <max> 21000 </max>
  <format> 0 </format>
</test>

<test>
  <var> SkeletalMuscle-Size.SolidMass </var>
  <datum> 5544 </datum>
  <min> 5500 </min>
  <max> 5600 </max>
  <format> 0 </format>
</test>

<test>
  <var> SkeletalMuscle-Size.ContractileProteinMass </var>
  <datum> 2772 </datum>
  <min> 2750 </min>
  <max> 2800 </max>
  <format> 0 </format>
</test>

<test>
  <var> SkeletalMuscle-Size.OtherMass </var>
  <datum> 2772 </datum>
  <min> 2750 </min>
  <max> 2800 </max>
  <format> 0 </format>
</test>

<test>
  <var> Skin-Size.LiquidMass </var>
  <datum> 1859 </datum>
  <min> 1800 </min>
  <max> 1900 </max>
  <format> 0 </format>
</test>

<test>
  <var> Skin-Size.SolidMass </var>
  <datum> 916 </datum>
  <min> 850 </min>
  <max> 950 </max>
  <format> 0 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->