<!--
   Script.Script @ Male_Normal | Initial_Values | Metabolism

   Created : 2012-03-06
   Revised : 2012-03-06
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<!--
<test>
  <var>  </var>
  <datum>  </datum>
  <min>  </min>
  <max>  </max>
  <format> 1 </format>
</test>
-->

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->