<!--
   Script.Script @ Male_Normal | Steady_State

   Created : 2012-03-05
   Revised : 2012-03-05
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center */
-->

<modeltitle/>
<timestamp/>

<stats_topic_reset/>
<stats_local_reset/>

<restart/>

<!-- Use 43200 and 2880 for 30 days -->

<gofor>
  <solutionint> 1440 </solutionint>
  <displayint> 60 </displayint>
</gofor>

<stats_topic> Male Normal | Steady State </stats_topic>

<comment> ==================================================== </comment>

<!-- End -->