Exercise_5_5_5_150W_Master.Script

Created : 2012-02-27
Revised : 2012-02-27
Author : Tom Coleman
Copyright : 2012-2012
By : University of Mississippi Medical Center

<stats_regional_reset/>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\Exercise_5_5_5_150W_Summary.HTML </filename> 
</open>

<modeltitle/>
<timestamp/>
<comment> Exercise 5-5-5 150W - Summary </comment>

<!--
<?include InitialValues_OrganMass.Script ?>
-->

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\Exercise_5_5_5_150W_Summary.HTML </filename> 
  <append/>
</open>
<stats_local> Local ... </stats_local>

<!--
<?include InitialValues_Pressures.Script ?>
-->

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\Exercise_5_5_5_150W_Summary.HTML </filename> 
  <append/>
</open>

<stats_local> Local ... </stats_local>
<stats_regional> Exercise 5-5-5 150W </stats_regional>

<comment> End </comment>
<close/>

End
