InitialValues_Master.Script

Created : 2012-02-27
Revised : 2012-02-27
Author : Tom Coleman
Copyright : 2012-2012
By : University of Mississippi Medical Center

<stats_regional_reset/>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\InitialValues_Summary.HTML </filename> 
</open>

<modeltitle/>
<timestamp/>
<comment> Initial Values - Summary </comment>

<?include InitialValues_BodyMass.Script ?>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\InitialValues_Summary.HTML </filename> 
  <append/>
</open>
<stats_local> Initial Values - Body Mass </stats_local>

<?include InitialValues_OrganMass.Script ?>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\InitialValues_Summary.HTML </filename> 
  <append/>
</open>
<stats_local> Initial Values - Organ Mass </stats_local>

<?include InitialValues_BloodPressures.Script ?>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\InitialValues_Summary.HTML </filename> 
  <append/>
</open>

<stats_local> Initial Values - Blood Pressures </stats_local>

<?include InitialValues_OrganComposition.Script ?>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\InitialValues_Summary.HTML </filename> 
  <append/>
</open>

<stats_local> Initial Values - Blood Pressures </stats_local>

<stats_regional> Inital Values </stats_regional>

<comment> End </comment>
<close/>

End
