Master.Script

Created : 2012-02-23
Revised : 2012-02-26
Author : Tom Coleman
Copyright : 2012-2012
By : University of Mississippi Medical Center

<script>
<script_to_html/>

<launch>
	<solver> J:\ModelSolver\Code\Model Solver.EXE </solver>
	<model> J:\HumModXML\HumMod.DES </model>
</launch>

<reset/>
<restart/>

<emit> HTML </emit>

<homepath> ../../../ </homepath>
<parent> Results.HTML </parent>

<?include InitialValues_OrganMass.Script ?>
<?include InitialValues_Pressures.Script ?>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\Summary.HTML </filename> 
</open>

<modeltitle/>
<timestamp/>

<comment> Summary </comment>

<files>
  <controller/>
  <solver/>
  <model/>
  <script/>
  <includedfiles/>
  <resultslog/>
</files>

<close/>

</script>

End
