Master.Script

Created : 2012-02-27
Revised : 2012-02-27
Author : Tom Coleman
Copyright : 2012-2012
By : University of Mississippi Medical Center

<script>
<script_to_html/>

<launch>
	<solver> J:\ModelSolver\Code\Model Solver.EXE </solver>
	<model> J:\HumModXML\HumMod.DES </model>
</launch>

<reset/>
<restart/>

<emit> HTML </emit>

<homepath> ../../../ </homepath>
<parent> Results.HTML </parent>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\Summary.HTML </filename> 
</open>

<modeltitle/>
<timestamp/>
<comment> Global Summary </comment>

<?include InitialValues_Master.Script ?>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\Summary.HTML </filename> 
  <append/>
</open>

<stats_regional> Initial Values </stats_regional>

<?include Exercise_5_5_5_150W_Master.Script ?>

<open>
  <filename> J:\HumModRepository\Validation\HumMod(2_0)\Results\Summary.HTML </filename> 
  <append/>
</open>

<stats_regional> Exercise 5-5-5 150W </stats_regional>

<stats_global> Total Stats </stats_global>

<files>
  <controller/>
  <solver/>
  <model/>
  <script/>
  <includedfiles/>
  <resultslog/>
</files>

<comment> End </comment>
<close/>

</script>

End
