<!--
   Script.Script @ Sandbox

   Created : 2012-03-06
   Revised : 2012-03-06
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<script>

<launch>
	<solver> J:\ModelSolver\Code\Model Solver.EXE </solver>
	<model> J:\HumModXML\HumMod.DES </model>
</launch>

<modeltitle/>
<timestamp/>

<reset/>
<restart/>

<roster>
  <var> System.X </var>
</roster>

<?include Circulation/Script.Script ?>
<?include Respiration/Script.Script ?>
<?include Metabolism/Script.Script ?>
<?include Body_Fluids/Script.Script ?>
<?include Electrolytes/Script.Script ?>
<?include Hormones/Script.Script ?>
<?include Nervous_System/Script.Script ?>
<?include Miscellaneous/Script.Script ?>

<showtotals/>

<newline/>

<?include Environment\Script.Script ?>

</script>

<!-- End -->