<!--
   Script.Script @ Male_Normal | Initial_Values | Blood_Pressures

   Created : 2012-03-04
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> SystemicArtys.Pressure </var>
  <datum> 97 </datum>
  <min> 95 </min>
  <max> 100 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicArtys.SBP </var>
  <datum> 120 </datum>
  <min> 118 </min>
  <max> 122 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicArtys.DBP </var>
  <datum> 80 </datum>
  <min> 78 </min>
  <max> 82 </max>
  <format> 1 </format>
</test>

<test>
  <var> Kidney-ArcuateArtery.Pressure </var>
  <datum> 95 </datum>
  <min> 93 </min>
  <max> 97 </max>
  <format> 1 </format>
</test>

<test>
  <var> GlomerulusFiltrate.Pressure </var>
  <datum> 60 </datum>
  <min> 57 </min>
  <max> 63 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicVeins.Pressure </var>
  <datum> 10 </datum>
  <min> 9 </min>
  <max> 11 </max>
  <format> 1 </format>
</test>

<test>
  <var> SplanchnicVeins.Pressure </var>
  <datum> 8 </datum>
  <min> 7 </min>
  <max> 9 </max>
  <format> 1 </format>
</test>

<test>
  <var> RightAtrium.Pressure </var>
  <datum> 2 </datum>
  <min> 1 </min>
  <max> 3 </max>
  <format> 1 </format>
</test>

<test>
  <var> PulmArty.Pressure </var>
  <datum> 14 </datum>
  <min> 13 </min>
  <max> 15 </max>
  <format> 1 </format>
</test>

<test>
  <var> PulmArty.SBP </var>
  <datum> 21 </datum>
  <min> 19 </min>
  <max> 23 </max>
  <format> 1 </format>
</test>

<test>
  <var> PulmArty.DBP </var>
  <datum> 9 </datum>
  <min> 8 </min>
  <max> 10 </max>
  <format> 1 </format>
</test>

<test>
  <var> PulmCapys.Pressure </var>
  <datum> 10 </datum>
  <min> 9 </min>
  <max> 11 </max>
  <format> 1 </format>
</test>

<test>
  <var> PulmVeins.Pressure </var>
  <datum> 7 </datum>
  <min> 6 </min>
  <max> 8 </max>
  <format> 1 </format>
</test>

<test>
  <var> LeftAtrium.Pressure </var>
  <datum> 6 </datum>
  <min> 5 </min>
  <max> 7 </max>
  <format> 1 </format>
</test>

<test>
  <var> Thorax.AvePressure </var>
  <datum> -4 </datum>
  <min> -5 </min>
  <max> -3 </max>
  <format> 1 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->