<!--
   Script.Script @ Female_Normal |  Initial_Values | Organ_Mass

   Created : 2012-03-04
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> Bone-Size.Mass </var>
  <datum> 8567 </datum>
  <min> 8400 </min>
  <max> 8700 </max>
  <format> 0 </format>
</test>

<test>
  <var> Brain-Size.Mass </var>
  <datum> 1198 </datum>
  <min> 1100 </min>
  <max> 1300 </max>
  <format> 0 </format>
</test>

<test>
  <var> Fat-Size.Mass </var>
  <datum> 19767 </datum>
  <min> 18700 </min>
  <max> 20700 </max>
  <format> 0 </format>
</test>

<test>
  <var> GITract-Size.Mass </var>
  <datum> 1018 </datum>
  <min> 900 </min>
  <max> 1100 </max>
  <format> 0 </format>
</test>

<test>
  <var> Kidney-Size.Mass </var>
  <datum> 264 </datum>
  <min> 230 </min>
  <max> 290 </max>
  <format> 1 </format>
</test>

<test>
  <var> LeftHeart-Size.Mass </var>
  <datum> 234 </datum>
  <min> 220 </min>
  <max> 250 </max>
  <format> 1 </format>
</test>

<test>
  <var> Liver-Size.Mass </var>
  <datum> 1558 </datum>
  <min> 1450 </min>
  <max> 1550 </max>
  <format> 0 </format>
</test>

<test>
  <var> OtherTissue-Size.Mass </var>
  <datum> 2816 </datum>
  <min> 2700 </min>
  <max> 2900 </max>
  <format> 0 </format>
</test>

<test>
  <var> RespiratoryMuscle-Size.Mass </var>
  <datum> 2876 </datum>
  <min> 2800 </min>
  <max> 3000 </max>
  <format> 0 </format>
</test>

<test>
  <var> RightHeart-Size.Mass </var>
  <datum> 48 </datum>
  <min> 42 </min>
  <max> 54 </max>
  <format> 1 </format>
</test>

<test>
  <var> SkeletalMuscle-Size.Mass </var>
  <datum> 14629 </datum>
  <min> 13500 </min>
  <max> 15500 </max>
  <format> 0 </format>
</test>

<test>
  <var> Skin-Size.Mass </var>
  <datum> 2217 </datum>
  <min> 2100 </min>
  <max> 2300 </max>
  <format> 0 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->