<!--
   Script.Script @ Male_Normal | Initial_Values | Body_Mass

   Created : 2012-03-04
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> Weight.Weight(kG) </var>
  <datum> 75 </datum>
  <min> 74 </min>
  <max> 76 </max>
  <format> 1 </format>
</test>

<test>
  <var> Weight.Weight(Lb) </var>
  <datum> 165 </datum>
  <min> 164 </min>
  <max> 166 </max>
  <format> 1 </format>
</test>

<test>
  <var> Adiposity.Mass </var>
  <datum> 16000 </datum>
  <min> 15500 </min>
  <max> 16500 </max>
  <format> 0 </format>
</test>

<test>
  <var> Muscularity.Mass </var>
  <datum> 26,400 </datum>
  <min> 26000 </min>
  <max> 27000 </max>
  <format> 1 </format>
</test>

<test>
  <var> OtherMass.Mass </var>
  <datum> 26000 </datum>
  <min> 25500 </min>
  <max> 26500 </max>
  <format> 0 </format>
</test>

<test>
  <var> Weight-Fluids.Total </var>
  <datum> 6525 </datum>
  <min> 6500 </min>
  <max> 6600 </max>
  <format> 0 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->