<!--
   Script.Script @ Male_Normal | Exercise_5_5_5_150W

   Created : 2012-03-04
   Revised : 2012-03-04
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<restart/>

<?path Male_Normal/Exercise_5_5_5_150W/ ?>

<?include Starting/Script.Script ?>
<?include 5_Minutes/Script.Script ?>
<?include 10_Minutes/Script.Script ?>
<?include 15_Minutes/Script.Script ?>

<showtotals/>

<!-- End -->