<!--
   Script.Script @ Female_Normal

   Created : 2012-03-04
   Revised : 2012-03-08
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<setvalue>
	<var> Gender.Index </var>
	<val> 1 </val>
</setvalue>

<?path Female_Normal ?>

<?include Initial_Values\Script.Script ?>
<!--<?include Exercise_5_5_5_150W\Script.Script ?>-->

<showtotals/>

<!-- End -->