<!--
   Script.Script @ Male_Normal | Initial_Values | Electrolytes

   Created : 2012-03-06
   Revised : 2012-03-07
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<cache> Units for blood ions are mEq/L </cache>

<test>
  <var> NaPool.[Na+(mEq/L)] </var>
  <datum> 140 </datum>
  <min> 137 </min>
  <max> 144 </max>
  <format> 1 </format>
</test>

<test>
  <var> KPool.[K+(mEq/L)] </var>
  <datum> 4.4 </datum>
  <min> 4.0 </min>
  <max> 4.8 </max>
  <format> 1 </format>
</test>

<test>
  <var>  ClPool.[Cl-(mEq/L)] </var>
  <datum> 103 </datum>
  <min> 90 </min>
  <max> 110 </max>
  <format> 1 </format>
</test>

<test>
  <var> LacPool.[Lac-(mEq/L)] </var>
  <datum> 1.0 </datum>
  <min> 0.2 </min>
  <max> 2.0 </max>
  <format> 1 </format>
</test>

<test>
  <var> KAPool.[KA(mMol/L)] </var>
  <datum> 0.1 </datum>
  <min> 0 </min>
  <max> 1 </max>
  <format> 1 </format>
</test>

<test>
  <var> SO4Pool.[SO4--(mEq/L)] </var>
  <datum> 0.3 </datum>
  <min> 0.2 </min>
  <max> 0.4 </max>
  <format> 1 </format>
</test>

<test>
  <var> PO4Pool.[PO4--(mEq/L)] </var>
  <datum> 0.2 </datum>
  <min> 0.1 </min>
  <max> 0.3 </max>
  <format> 1 </format>
</test>

<test>
  <var> CO2Veins.[HCO3(mEq/L)] </var>
  <datum> 25 </datum>
  <min> 20 </min>
  <max> 30 </max>
  <format> 1 </format>
</test>

<test>
  <var>  BloodIons.Protein </var>
  <datum> 16 </datum>
  <min> 12 </min>
  <max> 20 </max>
  <format> 1 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->