<!--
   Script.Script @ Male_Normal | Initial_Values | Circulation

   Created : 2012-03-06
   Revised : 2012-03-06
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> SystemicArtys.Pressure </var>
  <datum> 97 </datum>
  <min> 95 </min>
  <max> 100 </max>
  <format> 1 </format>
</test>

<test>
  <var> Heart-Rate.Rate </var>
   <datum> 72 </datum>
 <min> 68 </min>
  <max> 76 </max>
  <format> 1 </format>
</test>

<test>
  <var> CardiacOutput.Flow </var>
  <datum> 5400 </datum>
  <min> 5300 </min>
  <max> 5500 </max>
  <format> 1 </format>
</test>

<test>
  <var> CardiacOutput.StrokeVolume </var>
  <datum> 75 </datum>
  <min> 72 </min>
  <max> 78 </max>
  <format> 1 </format>
</test>

<test>
  <var> OrganFlow.PeripheralFlow </var>
  <datum> 3834 </datum>
  <min> 3730 </min>
  <max> 3930 </max>
  <format> 1 </format>
</test>

<test>
  <var> OrganFlow.HepaticVeinFlow </var>
  <datum> 1350 </datum>
  <min> 1300 </min>
  <max> 1400 </max>
  <format> 1 </format>
</test>

<test>
  <var> OrganFlow.CoronarySinusFlow </var>
  <datum> 216 </datum>
  <min> 200 </min>
  <max> 240 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicArtys.SBP </var>
  <datum> 120 </datum>
  <min> 115 </min>
  <max> 125 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicArtys.DBP </var>
  <datum> 80 </datum>
  <min> 75 </min>
  <max> 85 </max>
  <format> 1 </format>
</test>

<test>
  <var> SystemicVeins.Pressure </var>
  <datum> 10 </datum>
  <min> 8 </min>
  <max> 12 </max>
  <format> 1 </format>
</test>

<test>
  <var>  SplanchnicVeins.Pressure </var>
  <datum> 8 </datum>
  <min> 6 </min>
  <max> 10 </max>
  <format> 1 </format>
</test>

<test>
  <var> RightAtrium.Pressure </var>
  <datum> 2 </datum>
  <min> 0 </min>
  <max> 4 </max>
  <format> 1 </format>
</test>

<test>
  <var> LeftAtrium.Pressure </var>
  <datum> 6 </datum>
  <min> 4 </min>
  <max> 8 </max>
  <format> 1 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->