<!--
   Script.Script @ Female_Normal | Initial_Values

   Created : 2012-03-04
   Revised : 2012-03-04
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<stats_topic_reset/>

<?path Female_Normal\Initial_Values\ ?>

<?include Body_Mass\Script.Script ?>
<?include Organ_Mass\Script.Script ?>
<?include Blood_Pressures\Script.Script ?>
<?include Organ_Composition\Script.Script ?>

<stats_topic> Female Normal | Initial Values </stats_topic>

<!-- End -->