<!--
   Script.Script @ Male_Normal | Initial_Values | Body_Fluids

   Created : 2012-03-06
   Revised : 2012-03-06
   Author : Tom Coleman
   Copyright : 2012-2012
   By : University of Mississippi Medical Center
-->

<modeltitle/>
<timestamp/>

<test>
  <var> BodyH2O.TotalVol(L) </var>
  <datum> 44.3 </datum>
  <min> 43 </min>
  <max> 46 </max>
  <format> 1 </format>
</test>

<test>
  <var> ICFV.Vol(L) </var>
  <datum> 28.4 </datum>
  <min> 27 </min>
  <max> 30 </max>
  <format> 1 </format>
</test>

<test>
  <var>  ECFV.Vol(L) </var>
  <datum> 15.0 </datum>
  <min> 14 </min>
  <max> 16 </max>
  <format> 1 </format>
</test>

<test>
  <var> ExternalH2O.Other(L) </var>
  <datum> 1.0 </datum>
  <min> 0.8 </min>
  <max> 1.2 </max>
  <format> 1 </format>
</test>

<test>
  <var> BloodVol.Vol </var>
  <datum> 5400 </datum>
  <min> 5300 </min>
  <max> 5500 </max>
  <format> 1 </format>
</test>

<test>
  <var> RBCVol.Vol </var>
  <datum> 2380 </datum>
  <min> 2300 </min>
  <max> 2500 </max>
  <format> 1 </format>
</test>

<test>
  <var> PlasmaVol.Vol </var>
  <datum> 3020 </datum>
  <min> 2900 </min>
  <max> 3100 </max>
  <format> 1 </format>
</test>

<test>
  <var> BloodVol.Hct(%) </var>
  <datum> 44 </datum>
  <min> 42 </min>
  <max> 46 </max>
  <format> 1 </format>
</test>

<test>
  <var> OsmBody.[Osm(mOsm/L)]-CellWall </var>
  <datum> 280 </datum>
  <min> 270 </min>
  <max> 290 </max>
  <format> 1 </format>
</test>

<showtotals/>

<comment> ==================================================== </comment>

<showdetails/>

<!-- End -->